pool:
  name: 'GenesisPool-${project_name}'

stages:
  - stage: Build
    jobs: 
      - job: plan
        displayName: 'Plan Execution'
        steps:
          - checkout: self
          - script: | 
              terraform init
              terraform plan
            displayName: 'Run Tofu Plan'

      - job: apply
        displayName: 'Apply Execution'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        dependsOn:
          - plan
        steps:
          - checkout: self
          - script: |
              terraform init
              terraform apply -auto-approve
            displayName: 'Run Tofu Apply'
