pool:
  name: 'GenesisPool'


variables:
  - group: Terraform Secrets  


stages:
  - stage: Build
    jobs: 
      - job: plan
        displayName: 'Plan Execution'
        steps:
          - checkout: self
          - script: | 
              #export AZDO_PERSONAL_ACCESS_TOKEN=$SECRET_AZDO_PERSONAL_ACCESS_TOKEN
              # docker run --env-file <(env | grep AZDO) -v $(pwd):/app ghcr.io/inmetatrondheim/bootstrap-pinnacle:main plan
              env | grep AZDO
              terraform init
              terraform plan
            displayName: 'Run Tofu Plan'

      - job: apply
        displayName: 'Apply Execution'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        dependsOn:
          - plan
        steps:
          - checkout: self
          - script: |
              #export AZDO_PERSONAL_ACCESS_TOKEN=$SECRET_AZDO_PERSONAL_ACCESS_TOKEN
              # docker run --env-file <(env | grep AZDO) -v $(pwd):/app ghcr.io/inmetatrondheim/bootstrap-pinnacle:main apply
              env | grep AZDO
              terraform init
              terraform apply -auto-approve
            displayName: 'Run Tofu Apply'
