pool:
  name: 'GenesisPool-${project_name}'

trigger:
  branches:
    include:
      - '*'  # Triggers the pipeline on changes to any branch

stages:
  - stage: Build
    jobs: 
      - job: BuildProject
        steps:
          - checkout: self
          - template: earthly-install-template.yml 
          - script: |
              earthly +build

  - stage: ImmediateValidation
    jobs:
      - job: ImmediateTests
        steps:
          - checkout: self
          - template: earthly-install-template.yml 
          - script: |
              earthly +immediate-tests

  - stage: Publish
    jobs:
      - job: PublishArtifacts
        steps:
          - checkout: self
          - template: earthly-install-template.yml 
          - script: |
              earthly +publish


  - stage: DeploymentGate
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: ComprehensiveTests
        steps:
          - checkout: self
          - template: earthly-install-template.yml 
          - script: |
              earthly +comprehensive-tests
      - job: waitForValidation
        displayName: Wait for external validation
        pool: server
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          inputs:
            notifyUsers: |
              test@test.com
              example@test.com
            instructions: 'Please validate the build configuration and resume'
            onTimeout: 'resume'

  - stage: Deploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: DeployProject
        steps:
          - checkout: self
          - template: earthly-install-template.yml 
          - script: |
              earthly +deploy

